### ISSUE TITLE
Output Options

### ISSUE THREAD

**Issue by kc8pnd** [MacsInSpace/AirCastAirUpnpMacOS.pkg#1]
The application is working for what I want. The output devices only appear on itunes rather than the sound output icon.
![Screenshot at Jun 07 16-49-03](https://user-images.githubusercontent.com/15325086/172469720-4300be55-c4ae-453a-b739-c51a9b4ce504.png)

**Comment by MacsInSpace** [comment]
As mentioned iun the readme. This is not my code. I only packaged it. 
For software issue logging, head to: https://github.com/philippe44/AirConnect/issues/
